server:
  port: 8084
  
spring:
  application:
    name: API_GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotel/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/rating/**
         
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1001/eureka
      
      
okta:
  oauth2:
    issuer: https://dev-69692373.okta.com/oauth2/default
    audience: api://default
    client-id: 0oactn1cyfxlhNbYl5d7
    client-secret: 1H8RHeGhRNaP83UyrDxiMuOMMgcnQzS_MI4hPhCTSfp1VfvOFPcd9FlCvtjMal7i
    scopes: openid, profile, email, offline_access